### ISSUE TITLE
static_control id and user-specified IDs on all fields

### ISSUE THREAD

**Issue by sdahlbac** [bootstrap-ruby/bootstrap_form#245]
Rationale: I planned on using static fields for displaying additional data looked up via an autocomplete, but when I couldn't find the element via jQuery I started investigating and found that there is no `id` on a static_control. Hence I need to access the control via id. (If there are better ways in achieving this, I'm all ears)

Looking at test "static control" the expected result is:

``` html
<div class="form-group"><label class="control-label col-sm-2 required" for="user_email">Email</label><div class="col-sm-10"><p class="form-control-static">steve@example.com</p></div></div>
```

Note that the paragraph does not have an `id`, but the label has a `for` that is nonexisting.

I tried fixing this myself, but got lost in all the layers and couldn't find the id in `options[:id]`.

**Comment by JohnSmall** [comment]
This is an old one. But the issue is still there. 

All the other fields have ids attached to them. But not static_control. I'll guess it's because it's not provided by the underlying Rails form_for code. 

I need it to make writing tests easier. Checking something exists on page is easy if it has an id.

**Comment by mattbrictson** [comment]
It sounds like we need an easy way to place an `id` on the `<p>` element. Am I reading this requirement correctly?

If someone can figure out a way to do this, I'll gladly accept a PR!

**Comment by lcreid** [comment]
#357 fixed this for radio buttons and check boxes, but we still need to fix it for other form helpers. The label's `for` attribute doesn't pick up the user-specified ID. You can show the issue by adding this test to `test/bootstrap_form_test.rb`:
```
  test "bootstrap_form_for does not clobber custom options" do
    expected = <<-HTML.strip_heredoc
      <form accept-charset="UTF-8" action="/users" class="new_user" id="new_user" method="post" role="form">
        <input name="utf8" type="hidden" value="&#x2713;" />
        <div class="form-group">
          <label for="ID">Email</label>
          <input class="form-control" id="ID" name="NAME" type="text" />
        </div>
      </form>
    HTML
    assert_equivalent_xml expected, bootstrap_form_for(@user) { |f| f.text_field :email, name: 'NAME', id: "ID" }
  end
```
This issue is acute for people using `form_with` in Rails 5.1, so I'm going to add it to the 4.0.0 milestone.

**Comment by lcreid** [comment]
If someone (@duleorlovic ?) wants to work on this, let me know. Otherwise I'll do a PR for this in a day or two.

**Comment by duleorlovic** [comment]
@lcreid I updated your example since @user has validation on email `class="required"` and email value `value="steve@example.com"`, please look [here](https://github.com/bootstrap-ruby/bootstrap_form/pull/408/files#diff-c2a79125cc3e3e5b2b0ef57cac4583aaR104)
I added test for using  custom_id .
@lcreid what do you think, should we always set id on `<p>` element, even `id: 'custom_id'` is not provided  ?
I did not understand what you mean 'This issue is acute for people using form_with in Rails 5.1, so I'm going to add it to the 4.0.0 milestone.'.

**Comment by lcreid** [comment]
Personally, I think we should not generate markup unless it serves a purpose, so we wouldn't want to put an ID on a `<p>` element unless the user provided one. It looks to me like that's what you did, right?

I'm sorry I confused you with my comment. I was thinking about the larger issue of IDs in Rails 5.1. The underlying Rails helpers for `form_with` (unlike the helpers for `form_for`) don't add IDs to elements in Rails 5.1. This messes up a lot of people's Capybara scripts, and can also cause a lot of problem if you have any Javascript that was depending on those IDs. So allowing the user to specify an ID, while perhaps not ideal, is pretty necessary for people who want to use `form_with` in Rails 5.1. 

But all that doesn't really apply to the static control anyway, so when I mentioned it, I just confused things. Sorry.

**Comment by duleorlovic** [comment]
Yea, currently `id` is added only if user provides that parameter.

I was searching for issue regarding `form_with` but nothing found. Can you open new issue so we can work on that ? I see that [demo](https://github.com/bootstrap-ruby/bootstrap_form/blob/master/demo/app/views/bootstrap/form.html.erb) is 100 % functional (checkboxes do not work), maybe we can add additional section using `form_with`.
