### ISSUE TITLE
`static_control` needs to be updated to Bootstrap 4.

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#443]
Static controls are currently implemented as a `p` tag that contains the text of the field, styled with `.form-control-static`. That class no longer exists in Bootstrap 4. It appears that `.form-control-static` was intended to render static text vertically aligned with form labels, in horizontal layout and in-line layout forms.

In Bootstrap 4 there is a `.form-control-plaintext`, but it appears to be intended to be applied to a read-only input control (https://getbootstrap.com/docs/4.0/components/forms/#readonly-plain-text).

Simply applying `.form-control-plaintext` to text inside a `form_group` block will not render correctly if there's a validation error. In Bootstrap 4, the error highlight activates on `form-control.is-invalid`. The `p` tag has to have `.form-control.form-control-plaintext.is-invalid` for the invalid feedback to appear, and for the styling (red outline) to happen on the paragraph text. 

Further, if the intent of `static_control` is to show something that looks like an input field, but that the user can't change, why wouldn't the developer simply code the field with the `readonly` attribute, like [here](https://www.bootply.com/4rds6D8osj), or as a disabled input field?

Apologies if the above doesn't make sense. I've been staring at this too long, and I can't make it any better.

Would it make sense to do this:

- Change `static_control` to render a text input field with `.form-control-static` added to it
- Document that programmers should just use disabled or readonly inputs, with `.form-control-plaintext` if they don't want the border around the field
- If there isn't much use for `static_control`, deprecate it.

**Comment by parkeryoung** [comment]
Take everything I say with a grain of salt since I'm not super familiar with Bootstrap or this project, but after looking through this I had a few thoughts.

> Simply applying .form-control-plaintext to text inside a form_group block will not render correctly if there's a validation error.

Why would a validation error be rendered on a read-only field? I suppose it is possible, however it seems like that would be a flaw in the application design. I think worrying about what these render like together is unnecessary. Perhaps that's why they don't work well together to begin with.

> Further, if the intent of static_control is to show something that looks like an input field, but that the user can't change, why wouldn't the developer simply code the field with the readonly attribute, like here, or as a disabled input field?

That doesn't appear to be the intention though, it seems to be a desire to have a field not look like a field when it isn't meant to be edited. Perhaps to try to mitigate users frustration at not being able to edit a field?

Of the 3 options I think changing the `static_control` method is the best bet. The biggest curve ball is the `static_control` method accepts a block, I'm not sure what might be done with that. If we are looking for backwards compatibility, we could probably just put that into the `value` attribute of the field. Though if people put other tags in there for some reason that might be a problem. I can't imagine why someone might do that and it seems like it would be something that would be reasonably unsupported.

I'll try to write something up and you can take a look at the result and decide what you think.

**Comment by lcreid** [comment]
Good comments. Thanks!

> Why would a validation error be rendered on a read-only field? I suppose it is possible, however it seems like that would be a flaw in the application design. I think worrying about what these render like together is unnecessary

Yes, that's a good point. I don't like breaking existing code, and if someone *could* do it, someone probably *had* done it. 

> That doesn't appear to be the intention though, it seems to be a desire to have a field not look like a field when it isn't meant to be edited. Perhaps to try to mitigate users frustration at not being able to edit a field?

Good point. I hadn't thought about that.

I'll look at the PR and possibly comment further there.
