### ISSUE TITLE
static_control without an object fails

### ISSUE THREAD

**Issue by alec-implicitdesign** [bootstrap-ruby/bootstrap_form#505]
The example in the README actually fails.

```
<%= f.static_control label: "Custom Static Control" do %>
  Content Here
<% end %>
```

results in:

`ActionView::Template::Error (nil is not a symbol nor a string)`

**Comment by lcreid** [comment]
Thanks so much for taking the time to report this! It appears we didn't have a test case that covers this exact example, and the functionality got broken somewhere along the line.

**Comment by lcreid** [comment]
It turns out that this behaviour was a deliberate decision due to the changes needed to adapt to Bootstrap 4. See https://github.com/bootstrap-ruby/bootstrap_form/pull/446#issuecomment-370974725 (and the rest of the discussion around PR #446). The problem is that we didn't update the README. I'll fix it.
