### ISSUE TITLE
Test Fail on Edge AKA Rails 7

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#609]
Tests are currently failing on edge Rails, AKA Rail 7. If anyone is interested in working on a fix, please comment below.

Please branch from and submit pull requests to the ~`bootstrap-5`~ `main` branch. Thanks in advance.

**Comment by thimo** [comment]
Would love to take a look. With the release of 5.0 (congrats!) the branch should be against `main`, right?

**Comment by lcreid** [comment]
Yep. Thanks. I'll update the original comment. I'd love to see what you find.

**Comment by thimo** [comment]
`Rails.application.config.assets` as referenced in `demo/config/initializers/assets.rb` is no longer is available in Rails 7.0 main branch, probably because of recent Rails asset pipeline changes. Am going to figure out what the correct solution is here, staying backwards compatible for Rails 6.1, etc..
