### ISSUE TITLE
text_field options hide_label and label_as_placeholder not working

### ISSUE THREAD

**Issue by elbarto132** [bootstrap-ruby/bootstrap_form#621]
The options hide_label and label_as_placeholder on a text field aren't working.
Setting these options to true adds a class sr-only to the label, but it looks like this class doesn't exist in Bootstrap 5 anymore.

A workaround is to add this CSS:
.sr-only {
  display: none;
}

**Comment by lcreid** [comment]
Thanks for reporting this, and sorry you ran into this problem. I believe this is fixed by #615 . You can use the gem from GitHub until we do the next release. Change your `Gemfile` for `bootstrap_form` to:

```
gem "bootstrap_form", git: "https://github.com/bootstrap-ruby/bootstrap_form/"
```

and then do a `bundle update`.

Please let us know if that fixes the issue. Thanks again for taking the time to report this issue.

**Comment by elbarto132** [comment]
Using
`gem "bootstrap_form", git: "https://github.com/bootstrap-ruby/bootstrap_form/"`
throws a git error, but
`gem "bootstrap_form", git: "https://github.com/bootstrap-ruby/bootstrap_form/", branch: "main"`
works and it fixes the problem.

**Comment by lcreid** [comment]
Sorry. I thought it defaulted to `branch: "main"` but obviously it doesn't. Thanks for letting me know. I'll close this. If you think I shouldn't, please re-open it.

**Comment by rathboma** [comment]
A workaround for those wanting to use official releases (using scss):

```scss
.sr-only {
  @extend .visually-hidden;
}

```
